[package]
name = "{{crate_name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = "0.9.0"
# gdnative = { path = "../../godot-rust/gdnative" }

[build-dependencies]
gdnative-project-utils = "0.1.2"
